# Generated by Django 3.2.23 on 2023-12-21 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20231221_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeuser',
            name='role',
        ),
        migrations.AddField(
            model_name='employeeuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.employeerole'),
        ),
    ]
