# Generated by Django 3.2.23 on 2023-12-22 03:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assign_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='assign_to_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_Technology', to='accounts.Experty'),
        ),
    ]
