# Generated by Django 3.2.23 on 2023-12-22 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20231222_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_start_date', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('employee_end_date', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.project')),
            ],
        ),
    ]
