# Generated by Django 3.2.23 on 2023-12-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_employeeproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeetask',
            old_name='title',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='employeetask',
            name='task_status',
        ),
    ]
