# Generated by Django 3.2.23 on 2023-12-24 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20231224_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetask',
            name='task_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.taskstatus'),
        ),
    ]
