# Generated by Django 3.2.23 on 2023-12-24 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_employeetask_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskstatus',
            old_name='status',
            new_name='task_status',
        ),
    ]
