# Generated by Django 3.2.23 on 2023-12-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_status_taskstatus_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetask',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
