# Generated by Django 3.2.23 on 2023-12-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_employeetask_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetask',
            name='actual_time',
            field=models.CharField(blank=True, default='0:0', max_length=100, null=True),
        ),
    ]
